'use client';
import {Archive,BookOpen,Check,Clock3,Copy,ImagePlus,Pause,Play,Plus,SquarePen} from 'lucide-react';
import {clock,dateLabel,duration,money,number,Skein,statusLabels} from '../primitives';
import type {Project,Session} from '@/lib/models';
import {LegacyCosts,SourceNotes} from '../imported-data';
import {useWorkshop} from '../workshop-context';

function TimerPanel({p}:{p:Project}){
 const {active,activeSeconds,busy,act,open}=useWorkshop();const running=active?.project_id===p.id;
 return <section className="timer-panel"><span className="section-label"><Clock3 size={18}/> Время за вязанием</span><div className="timer-value">{clock(p.seconds+(running?activeSeconds:0))}</div><p>{running?'Таймер работает, даже если закрыть вкладку.':'Каждая минута складывается в вашу работу.'}</p><div className="row"><button className="button primary" disabled={busy||p.archived||['completed','cancelled'].includes(p.status)} onClick={()=>act(running?{type:'timer.stop',session_id:active!.id}:{type:'timer.start',id:p.id},running?'Таймер на паузе':'Таймер запущен')}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Пауза':'Начать вязать'}</button><button className="button secondary" disabled={busy} onClick={()=>open({type:'time',project:p})}>Ввести время</button></div></section>;
}
export default function ProjectDetail({current}:{current:Project}){
 const {state,busy,active,activeSeconds,act,open,navigate,selectProject,upload}=useWorkshop();
 const sessionSeconds=(s:Session)=>s.manual_seconds??(s.ended_at?(Date.parse(s.ended_at)-Date.parse(s.started_at!))/1000:activeSeconds);
 const photos=state.photos.filter(p=>p.project_id===current.id);
 const usage=state.usage.filter(u=>u.project_id===current.id);
 const sessions=state.sessions.filter(s=>s.project_id===current.id);
 const shownSeconds=current.seconds+(active?.project_id===current.id?activeSeconds:0);
 return <>
 <div className="detail-meta"><span className={`badge ${current.status}`}>{statusLabels[current.status]}</span>{current.archived&&<span className="badge">В архиве</span>}{current.historical&&<span className="badge">Расход учтен ранее</span>}<span>Начало: {dateLabel(current.start_date)}</span><span>Завершение: {current.end_date?dateLabel(current.end_date):current.end_month?`${current.end_month.slice(5)}.${current.end_month.slice(0,4)} (месяц)`:'Не указано'}</span></div>
 <div className="detail-layout"><div className="detail-main">
 <section className="panel photos-panel"><div className="panel-title"><h2>Фотографии</h2><label className="button secondary upload-label"><ImagePlus size={16}/>{busy?'Загрузка…':'Добавить фото'}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,current);e.target.value='';}}/></label></div>{photos.length?<div className="photo-gallery">{photos.map(photo=><a key={photo.id} href={`/api/photos/${photo.id}`} target="_blank" rel="noreferrer"><img src={`/api/photos/${photo.id}`} alt={current.title}/></a>)}</div>:<div className="photo-empty"><Skein/><p>Сохраните первый стежок и готовую работу</p></div>}</section>
 <section className="panel"><div className="panel-title"><h2>Пряжа в проекте</h2><button className="button secondary" disabled={busy||!state.yarns.length} onClick={()=>open({type:'consume',project:current})}><Plus size={16}/>Указать расход</button></div>{!state.yarns.length?<p className="muted">Сначала <button className="inline-link" onClick={()=>{navigate('yarn');open({type:'yarn'});}}>добавьте пряжу в банк</button>.</p>:usage.length?<div className="materials">{usage.map(u=>{const y=state.yarns.find(y=>y.id===u.yarn_id)!;return <div className="material" key={u.yarn_id}><span className="swatch" style={{background:y.color_hex}}/><div><strong>{y.manufacturer} {y.name}</strong><small>{y.color}</small></div><strong>{number(u.grams)} г</strong><button className="icon-button" title="Изменить расход" aria-label={`Изменить расход ${y.name}`} onClick={()=>open({type:'consume',project:current,yarnId:y.id})}><SquarePen size={16}/></button></div>;})}</div>:<p className="muted">Выберите пряжу и укажите, сколько граммов уже использовали.</p>}{current.quantity>1&&<p className="hint">Здесь указан расход на всю партию из {current.quantity} шт.</p>}</section>
 <section className="panel"><div className="panel-title"><h2>Сеансы работы</h2><span className="muted">{sessions.length}</span></div>{sessions.length?<div className="sessions">{sessions.map(s=><div key={s.id}><Clock3 size={18}/><div><strong>{duration(sessionSeconds(s))}{s.started_at&&!s.ended_at&&' · идет сейчас'}</strong><small>{s.note||(s.manual_seconds?'Добавлено вручную':new Date(s.started_at!).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</small></div>{!(s.started_at&&!s.ended_at)&&<button className="icon-button" aria-label="Исправить сеанс" onClick={()=>open({type:'time',project:current,session:s})}><SquarePen size={15}/></button>}</div>)}</div>:<p className="muted">Запустите таймер или добавьте время вручную.</p>}</section>
 <SourceNotes project={current}/>
 {current.notes&&<section className="panel"><h2>Параметры и заметки</h2><p className="notes">{current.notes}</p></section>}
 </div><div className="detail-side"><TimerPanel p={current}/>
 {current.source_data?<LegacyCosts project={current}/>:<section className="panel cost-panel"><h2>Стоимость работы</h2><dl><div><dt>Пряжа</dt><dd>{money(current.yarn_cost)}</dd></div><div><dt>Другие материалы</dt><dd>{money(current.other_cost)}</dd></div><div><dt>Работа · {money(current.rate)}/ч</dt><dd>{money(shownSeconds/3600*Number(current.rate))}</dd></div><div className="cost-total"><dt>{current.cost_incomplete?'Известная часть':'Расчетная стоимость'}</dt><dd>{money(Number(current.yarn_cost)+Number(current.other_cost)+shownSeconds/3600*Number(current.rate))}</dd></div>{current.quantity>1&&<div><dt>В среднем за штуку</dt><dd>{money((Number(current.yarn_cost)+Number(current.other_cost)+current.seconds/3600*Number(current.rate))/current.quantity)}</dd></div>}<div><dt>Назначенная цена / шт.</dt><dd>{current.price===null?'Не задана':money(current.price)}</dd></div></dl>{current.cost_incomplete&&<p className="notice">Стоимость части пряжи неизвестна. Итог неполный.</p>}</section>}
 <section className="project-actions">{!current.archived&&<><label className="field"><span>Статус проекта</span><select aria-label="Статус проекта" value={current.status} disabled={busy} onChange={e=>act({type:'project.status',id:current.id,version:current.version,status:e.target.value},'Статус обновлен')}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{current.status!=='completed'&&<button className="button primary full" disabled={busy} onClick={()=>act({type:'project.status',id:current.id,version:current.version,status:'completed'},'Изделие готово!')}><Check size={17}/>Завершить проект</button>}</>}
 <button className="button secondary full" disabled={busy} onClick={async()=>{const r=await act({type:'project.repeat',id:current.id},'Создан новый проект по образцу');if(r?.id)selectProject(r.id);}}><Copy size={16}/>Связать еще раз</button><button className="text-button" disabled={busy} onClick={()=>act({type:'template.save',id:current.id},'Шаблон сохранен')}><BookOpen size={16}/>Сохранить как шаблон</button><button className="text-button" disabled={busy} onClick={()=>act({type:'project.archive',id:current.id,version:current.version,archived:!current.archived},current.archived?'Проект возвращен из архива':'Проект в архиве')}><Archive size={16}/>{current.archived?'Вернуть из архива':'Убрать в архив'}</button></section>
 </div></div>
 </>;
}
