'use client';
import {ArrowUpRight,Plus,Search} from 'lucide-react';
import {dateLabel,Empty,money,number,Skein} from '../primitives';
import type {Yarn} from '@/lib/models';
import {ImportedPurchases} from '../imported-data';
import {useWorkshop} from '../workshop-context';

export function YarnList(){
 const {state,search,setSearch,open,selectYarn}=useWorkshop();
 return <><div className="toolbar"><p className="muted">{state.yarns.length} цветов · {number(state.yarns.reduce((s,y)=>s+Number(y.balance),0))} г в запасе</p><label className="search"><Search size={17}/><input aria-label="Поиск пряжи" placeholder="Название, цвет или состав" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{state.yarns.length?<div className="yarn-grid">{state.yarns.filter(y=>`${y.manufacturer} ${y.name} ${y.color} ${y.composition}`.toLowerCase().includes(search.toLowerCase())).map(y=><button className="yarn-card" key={y.id} onClick={()=>selectYarn(y.id)}><div className="yarn-art" style={{background:`${y.color_hex}15`}}><Skein color={y.color_hex}/></div><div><small>{y.manufacturer}</small><h3>{y.name}</h3><p>{y.color}</p><div className="yarn-card-bottom"><strong>{number(y.balance)} <small>г</small></strong><span>{number(y.skein_weight)} г / {y.skein_length?`${number(y.skein_length)} м`:'метраж не указан'}</span></div></div></button>)}</div>:<Empty title="Ваша коллекция начинается с мотка" description="Добавьте пряжу, которую уже купили. Цвет, состав и остаток будут под рукой, когда появится новая идея."><button className="button primary" onClick={()=>open({type:'yarn'})}><Plus size={18}/>Добавить первую пряжу</button></Empty>}</>;
}
export function YarnDetail({yarn}:{yarn:Yarn}){
 const {state,open}=useWorkshop();
 const receipts=state.receipts.filter(r=>r.yarn_id===yarn.id);
 return <><div className="yarn-summary"><Skein color={yarn.color_hex}/><div><p className="muted">Осталось в банке</p><strong>{number(yarn.balance)} <span>г</span></strong><p>{yarn.composition}</p><small>{number(yarn.skein_weight)} г в мотке{yarn.skein_length?` · ${number(yarn.skein_length)} м`:''}</small></div></div><section className="panel"><div className="panel-title"><h2>Поступления</h2><span className="muted">Отдельная запись для каждой покупки</span></div>{receipts.length?<div className="table-wrap"><table><thead><tr><th>Дата / партия</th><th>Получено</th><th>Осталось</th><th>Стоимость</th><th/></tr></thead><tbody>{receipts.map(r=><tr key={r.id}><td>{dateLabel(r.purchased_on)}<small>{r.dye_lot||r.note}</small></td><td>{number(r.grams)} г</td><td>{number(r.balance)} г</td><td>{r.cost===null?'Неизвестна':money(r.cost)}</td><td><button className="text-button" onClick={()=>open({type:'adjust',receipt:r})}>Уточнить остаток</button></td></tr>)}</tbody></table></div>:<div className="inline-empty"><p>Укажите, сколько этой пряжи у вас есть.</p><button className="button primary" onClick={()=>open({type:'receive',yarn})}><Plus size={17}/>Добавить поступление</button></div>}</section><section className="panel"><h2>История движения</h2><div className="movement-list">{state.movements.filter(m=>m.yarn_id===yarn.id).map(m=><div key={m.id}><span className={Number(m.grams)>0?'movement-icon positive':'movement-icon'}>{Number(m.grams)>0?<Plus size={17}/>:<ArrowUpRight size={17}/>}</span><div><strong>{{receipt:'Поступление',consumption:'Расход на изделие',return:'Возврат пряжи',adjustment:'Уточнение остатка'}[m.kind]}</strong><small>{state.projects.find(p=>p.id===m.project_id)?.title??m.reason??''} · {new Date(m.created_at).toLocaleDateString('ru-RU')}</small></div><b className={Number(m.grams)>0?'positive':''}>{Number(m.grams)>0?'+':''}{number(m.grams)} г</b></div>)}</div></section><ImportedPurchases yarn={yarn} state={state}/></>;
}
