'use client';
import {useEffect,useState} from 'react';
import {FileSpreadsheet,Upload,Check,ArrowLeft} from 'lucide-react';
import {number,duration,money} from './primitives';
import type {ImportBatch,ImportKind,ImportResult} from '@/lib/import-types';

type ImportListItem=Pick<ImportBatch,'id'|'source_name'|'status'|'created_at'|'result'>&{totals:ImportBatch['preview']['totals']};
const labels:Record<ImportKind,string>={template:'Шаблоны',purchase:'Покупки пряжи',project:'Выполненные изделия'};
export default function ImportPanel({onImported}:{onImported:()=>Promise<void>}){
 const [batch,setBatch]=useState<ImportBatch|null>(null);const [list,setList]=useState<ImportListItem[]>([]);const [selected,setSelected]=useState<string[]>([]);
 const [kind,setKind]=useState<ImportKind>('project');const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<ImportResult|null>(null);
 async function loadList(){const r=await fetch('/api/import');const data=await r.json();if(!r.ok)throw Error(data.error);setList(data);}
 useEffect(()=>{loadList().catch(e=>setError(e.message));},[]);
 function show(data:ImportBatch){setBatch(data);setSelected(data.preview.rows.filter(r=>!r.errors.length).map(r=>r.key));setAck(false);setResult(data.result);setError('');}
 async function upload(file:File){setBusy(true);setError('');try{const body=new FormData();body.set('file',file);const r=await fetch('/api/import',{method:'POST',body});const data=await r.json();if(!r.ok)throw Error(data.error);show(data);await loadList();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reopen(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/import?id=${id}`);const data=await r.json();if(!r.ok)throw Error(data.error);show(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){if(!batch)return;setBusy(true);setError('');try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:batch.id,selected,acknowledge:ack})});const data=await r.json();if(!r.ok)throw Error(data.error);setResult(data);setBatch({...batch,status:'committed',result:data});await onImported();await loadList();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const rows=batch?.preview.rows.filter(r=>r.kind===kind)??[];
 const warnings=batch?.preview.rows.filter(r=>selected.includes(r.key)&&r.warnings.length).length??0;
 return <div className="import-panel">
 {!batch?<><section className="panel import-intro"><FileSpreadsheet size={36}/><h2>Из таблицы — в мастерскую</h2><p>Перенесите шаблоны, выполненные изделия и историю покупок из вашей книги учета. Сначала вы увидите все строки и замечания.</p><label className="button primary upload-label"><Upload size={17}/>{busy?'Читаю таблицу…':'Выбрать XLSX'}<input aria-label="Выбрать XLSX" type="file" accept=".xlsx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);e.target.value='';}}/></label><p className="hint">До 5 МБ. Поддерживается структура книги «Вязание.xlsx». Текущие остатки вводятся отдельно после переноса.</p></section>{list.length>0&&<section className="panel"><h2>Загруженные таблицы</h2><div className="import-history">{list.map(item=><button disabled={busy} key={item.id} onClick={()=>reopen(item.id)}><FileSpreadsheet size={21}/><span><strong>{item.source_name}</strong><small>{item.totals.projects} записей изделий · {item.status==='committed'?'Перенесено':'Ожидает переноса'}</small></span></button>)}</div></section>}</>:<>
 <button className="back-link" onClick={()=>{setBatch(null);setError('');}} disabled={busy}><ArrowLeft size={16}/>Загруженные таблицы</button>
 <section className="panel"><div className="panel-title"><h2>{batch.source_name}</h2><span className="badge">{batch.status==='committed'?'Перенесено':'Предварительный просмотр'}</span></div>
 <div className="import-summary"><span><strong>{batch.preview.totals.templates}</strong> шаблонов</span><span><strong>{batch.preview.totals.projects}</strong> записей изделий</span><span><strong>{batch.preview.totals.units}</strong> вещей</span><span><strong>{batch.preview.totals.purchases}</strong> покупок</span></div>
 {batch.preview.warnings.map((w,i)=><p className="hint" key={i}>{w}</p>)}
 {result&&<div className="import-result" role="status"><Check size={20}/><div><strong>Перенос завершен</strong><p>{result.templates} шаблонов, {result.projects} проектов ({result.units} вещей), {result.purchases} покупок, {result.yarns} новых карточек пряжи.</p><p>Остатки не изменились. Исключено строк: {result.excluded.length}.</p>{result.excluded.length>0&&<details><summary>Исключенные строки</summary><p>{result.excluded.join(', ')}</p></details>}</div></div>}
 </section>
 <div className="toolbar"><div className="filters">{Object.entries(labels).map(([k,l])=><button key={k} className={kind===k?'active':''} onClick={()=>setKind(k as ImportKind)}>{l}</button>)}</div><span className="muted">{batch.status==='preview'?`Выбрано ${selected.length} из ${batch.preview.rows.length}`:'Сохраненные значения источника'}</span></div>
 <div className="import-rows">{rows.map(row=><article className="panel import-row" key={row.key}><div className="import-row-heading">{batch.status==='preview'&&<input aria-label={`Перенести строку ${row.row}`} type="checkbox" checked={selected.includes(row.key)} disabled={busy||!!row.errors.length} onChange={e=>setSelected(e.target.checked?[...selected,row.key]:selected.filter(k=>k!==row.key))}/>}<div><small>{row.sheet} · строка {row.row}</small><h3>{row.title}</h3></div><span className="badge">{row.kind==='project'?`${row.quantity} шт.`:row.kind==='purchase'?`${number(row.quantity)} мотков`:'Модель'}</span></div>
 <div className="import-row-facts">{row.kind==='project'?<><span>Завершено: {row.date??row.month??'неизвестно'}</span><span>Время: {row.seconds===null?'неизвестно':duration(row.seconds)}</span><span>Материалы: {row.materialCost===null?'неизвестно':`${money(row.materialCost)} из Excel`}</span></>:row.kind==='purchase'?<><span>{row.color||'Цвет не указан'} · № {row.code||'нет'}</span><span>Куплено: {row.purchasedGrams===null?'неизвестно':`${number(row.purchasedGrams)} г`}</span><span>Стоимость: {row.purchaseCost===null?'неизвестна':money(row.purchaseCost)}</span></>:<span>{row.yarnName} · {row.seconds===null?'Время не указано':duration(row.seconds)}</span>}</div>
 {row.errors.map((w,i)=><p className="form-error" key={i}>{w}</p>)}{row.warnings.length>0&&<ul className="import-warnings">{row.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}<details><summary>Параметры из таблицы</summary><p className="notes">{row.notes}</p></details></article>)}</div>
 {batch.status==='preview'&&<section className="panel import-controls">{warnings>0&&<label className="check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>Я просмотрел замечания к {warnings} строкам. Сохранить спорные значения с пометками из Excel.</span></label>}<p className="hint">Будут добавлены только выбранные строки. Старые изделия не спишут пряжу; покупки сохранятся как история. Повтор того же переноса не создаст дубликаты.</p><button className="button primary" disabled={busy||!selected.length||(warnings>0&&!ack)} onClick={commit}>{busy?'Переношу…':`Перенести выбранные строки (${selected.length})`}</button></section>}
 </>}{error&&<p className="form-error" role="alert">{error}</p>}
 </div>;
}
