'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Archive,ArrowLeft,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronRight,Clock3,Copy,Download,FolderHeart,ImagePlus,LayoutGrid,LoaderCircle,MoreHorizontal,Pause,Play,Plus,Search,Settings2,SlidersHorizontal,Spool,SquarePen,X} from 'lucide-react';
import Forms,{type FormKind} from './forms';
import {clock,dateLabel,duration,Empty,money,number,purposeLabels,Skein,statusLabels} from './primitives';
import type {State,Project,Session,Yarn} from '@/lib/models';
import ImportPanel from './import-panel';
import {ImportedPurchases,LegacyCosts,SourceNotes} from './imported-data';

type Tab='projects'|'yarn'|'finished'|'templates'|'import';
const tabs:[Tab,string,typeof LayoutGrid][]=[['projects','Мои проекты',LayoutGrid],['yarn','Банк пряжи',Spool],['finished','Готовые изделия',CheckCheck],['templates','Шаблоны',BookOpen],['import','Импорт Excel',Download]];
export default function Studio(){
 const [state,setState]=useState<State|null>(null);const [loadError,setLoadError]=useState('');
 const [tab,setTab]=useState<Tab>('projects');const [selected,setSelected]=useState<string|null>(null);const [selectedYarn,setSelectedYarn]=useState<string|null>(null);
 const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [form,setForm]=useState<FormKind|null>(null);
 const [error,setError]=useState('');const [toast,setToast]=useState('');const [busy,setBusy]=useState(false);const [now,setNow]=useState(Date.now());const offset=useRef(0);const keys=useRef(new Map<string,string>());
 const refresh=useCallback(async()=>{
  const response=await fetch('/api/state',{cache:'no-store'});const data=await response.json();
  if(!response.ok)throw Error(data.error);offset.current=Date.parse(data.serverNow)-Date.now();setState(data);setLoadError('');
 },[]);
 useEffect(()=>{refresh().catch(e=>setLoadError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),15000);const tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(timer);clearInterval(tick);};},[refresh]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 function open(value:FormKind){setError('');setForm(value);}
 async function command(value:Record<string,unknown>){
  const body=JSON.stringify(value);let key=keys.current.get(body);if(!key){key=crypto.randomUUID();keys.current.set(body,key);}
  const response=await fetch('/api/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,command:value})});
  const data=await response.json();if(!response.ok){if(response.status<500)keys.current.delete(body);throw Error(data.error+(data.details?' '+data.details.join('; '):''));}
  await refresh();keys.current.delete(body);return data as {id?:string};
 }
 async function act(value:Record<string,unknown>,message='Сохранено'){
  if(busy)return;setBusy(true);setError('');try{const result=await command(value);setToast(message);return result;}catch(e){setToast(e instanceof Error?e.message:'Не удалось сохранить. Повторите действие.');}finally{setBusy(false);}
 }
 async function save(value:Record<string,unknown>){
  setBusy(true);setError('');try{
   const result=await command(value);setForm(null);setToast('Сохранено');
   if(value.type==='project.create'){setTab('projects');setSelected(result.id!);}
   if(value.type==='yarn.create'){setTab('yarn');setSelectedYarn(result.id!);setToast('Пряжа добавлена. Теперь пополните запас.');}
  }catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить. Повторите действие.');}finally{setBusy(false);}
 }
 function navigate(next:Tab){setTab(next);setSelected(null);setSelectedYarn(null);setSearch('');setFilter('all');}
 const active=state?.sessions.find(s=>s.started_at&&!s.ended_at);
 const activeProject=state?.projects.find(p=>p.id===active?.project_id);
 const activeSeconds=active?Math.max(0,Math.floor((now+offset.current-Date.parse(active.started_at!))/1000)):0;
 const current=state?.projects.find(p=>p.id===selected);
 const yarn=state?.yarns.find(y=>y.id===selectedYarn);
 const headerTitle=current?.title??yarn?.name??({projects:'Мои проекты',yarn:'Банк пряжи',finished:'Готовые изделия',templates:'Шаблоны',import:'Импорт Excel'}[tab]);
 const filtered=state?.projects.filter(p=>{
  if(tab==='finished'&&p.status!=='completed')return false;
  if(filter==='archive'?!p.archived:p.archived)return false;
  if(!['all','archive'].includes(filter)&&p.status!==filter)return false;
  return `${p.title} ${p.category}`.toLowerCase().includes(search.toLowerCase());
 })??[];
 const totalHours=state?.projects.reduce((sum,p)=>sum+p.seconds,0)??0;
 const completedCount=state?.projects.filter(p=>p.status==='completed').reduce((sum,p)=>sum+p.quantity,0)??0;
 async function upload(file:File,p:Project){
  setBusy(true);try{
   const body=new FormData();body.set('file',file);body.set('project_id',p.id);
   const response=await fetch('/api/photos',{method:'POST',body});const data=await response.json();if(!response.ok)throw Error(data.error);await refresh();setToast('Фотография добавлена');
  }catch(e){setToast(e instanceof Error?e.message:'Не удалось добавить фото');}finally{setBusy(false);}
 }
 function projectCard(p:Project){const photo=state!.photos.find(photo=>photo.project_id===p.id);const use=state!.usage.filter(u=>u.project_id===p.id);return <button className="project-card" key={p.id} onClick={()=>setSelected(p.id)}>
  <div className={`project-image illustration-${p.category==='Шарф'?'scarf':p.category==='Шапка'?'hat':'other'}`}>{photo?<img src={`/api/photos/${photo.id}`} alt={p.title}/>:<div className="knit-illustration"><Skein color={state!.yarns.find(y=>y.id===use[0]?.yarn_id)?.color_hex??'#9880ae'}/><span>{p.category}</span></div>}<span className={`badge ${p.status}`}>{statusLabels[p.status]}</span></div>
  <div className="project-card-body"><div className="eyeline">{purposeLabels[p.purpose]}{p.quantity>1&&<span>{p.quantity} шт.</span>}</div><h3>{p.title}</h3><div className="card-footer"><span><Clock3 size={14}/>{duration(p.seconds+(active?.project_id===p.id?activeSeconds:0))}</span><span className="color-dots">{use.slice(0,4).map(u=><i key={u.yarn_id} style={{background:state!.yarns.find(y=>y.id===u.yarn_id)?.color_hex}}/>)}</span></div></div>
 </button>;}
 function timerPanel(p:Project){const running=active?.project_id===p.id;return <section className="timer-panel"><span className="section-label"><Clock3 size={18}/> Время за вязанием</span><div className="timer-value">{clock(p.seconds+(running?activeSeconds:0))}</div><p>{running?'Таймер работает, даже если закрыть вкладку.':'Каждая минута складывается в вашу работу.'}</p><div className="row"><button className="button primary" disabled={busy||p.archived||['completed','cancelled'].includes(p.status)} onClick={()=>act(running?{type:'timer.stop',session_id:active!.id}:{type:'timer.start',id:p.id},running?'Таймер на паузе':'Таймер запущен')}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Пауза':'Начать вязать'}</button><button className="button secondary" disabled={busy} onClick={()=>open({type:'time',project:p})}>Ввести время</button></div></section>;}
 function sessionSeconds(s:Session){return s.manual_seconds??(s.ended_at?(Date.parse(s.ended_at)-Date.parse(s.started_at!))/1000:activeSeconds);}
 return <div className="studio">
 <aside className="sidebar"><a className="brand" href="/" aria-label="Петелька, главная"><img src="/icon.svg" alt=""/><span>петелька<small>моя мастерская</small></span></a><nav aria-label="Разделы мастерской">{tabs.map(([id,title,Icon])=><button key={id} className={tab===id?'nav-item selected':'nav-item'} onClick={()=>navigate(id)}><Icon size={19}/><span>{title}</span>{id==='projects'&&state&&<b>{state.projects.filter(p=>!p.archived).length}</b>}</button>)}</nav>
 <div className="sidebar-note"><Skein color="#b5a3c4"/><p>От первого мотка<br/>до последней петли.</p></div><div className="sidebar-bottom"><button className="nav-item" onClick={()=>state&&open({type:'settings'})}><Settings2 size={18}/>Настройки</button><span className="local-status"><i/> Личная мастерская</span></div></aside>
 <main>
 <div className="topline"><span>Место для ваших идей и теплых вещей</span><span className="today">{new Date(now).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</span></div>
 {active&&activeProject&&<div className="running-bar"><span className="pulse"/><button onClick={()=>{setTab('projects');setSelected(activeProject.id);}}>{activeProject.title}</button><strong>{clock(activeSeconds)}</strong><button className="icon-button" disabled={busy} aria-label="Остановить активный таймер" onClick={()=>act({type:'timer.stop',session_id:active.id},'Таймер на паузе')}><Pause size={18}/></button></div>}
 {(current||yarn)&&<button className="back-link" onClick={()=>{setSelected(null);setSelectedYarn(null);}}><ArrowLeft size={16}/> {current?'Все проекты':'Вся пряжа'}</button>}
 <header className="page-header"><div><h1>{headerTitle}</h1><p>{current?`${current.category} · ${purposeLabels[current.purpose]}${current.quantity>1?` · ${current.quantity} шт.`:''}`:yarn?`${yarn.manufacturer} · ${yarn.color}`:({projects:'Все, что вы создаете, в одном месте.',yarn:'Каждый цвет на своем месте. Каждый грамм учтен.',finished:'Вещи, в которых осталось ваше тепло.',templates:'Сохраняйте удачные модели и вяжите их снова.',import:'Сохраните историю и начните новый учет.'}[tab])}</p></div>
 {state&&!current&&!yarn&&tab!=='import'&&<button className="button primary" onClick={()=>tab==='yarn'?open({type:'yarn'}):open({type:'project'})}><Plus size={18}/>{tab==='yarn'?'Добавить пряжу':'Новый проект'}</button>}
 {current&&<button className="button secondary" onClick={()=>open({type:'project',project:current})}><SquarePen size={16}/>Редактировать</button>}
 {yarn&&<button className="button primary" onClick={()=>open({type:'receive',yarn})}><Plus size={18}/>Пополнить запас</button>}
 </header>
 {!state?<div className="loading-state">{loadError?<><p role="alert">{loadError}</p><button className="button secondary" onClick={()=>refresh().catch(e=>setLoadError(e.message))}>Повторить загрузку</button></>:<><LoaderCircle className="spinner"/>Открываю мастерскую…</>}</div>:<>
 {!current&&!yarn&&tab==='projects'&&<div className="overview-strip"><div><span className="stat-symbol lavender"><FolderHeart size={20}/></span><span><strong>{state.projects.filter(p=>['active','paused'].includes(p.status)&&!p.archived).length}</strong><small>проектов в работе</small></span></div><div><span className="stat-symbol sage"><CheckCheck size={20}/></span><span><strong>{completedCount}</strong><small>изделий готово</small></span></div><div><span className="stat-symbol peach"><Clock3 size={20}/></span><span><strong>{number((totalHours+activeSeconds)/3600)}</strong><small>часов за вязанием</small></span></div></div>}
 {!current&&!yarn&&['projects','finished'].includes(tab)&&<>
  <div className="toolbar"><div className="filters" aria-label="Фильтр проектов">{(tab==='finished'?[['all','Все'],['archive','Архив']]:[['all','Все проекты'],['active','В работе'],['planned','В планах'],['paused','На паузе'],['archive','Архив']]).map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Поиск проектов" placeholder="Найти проект" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
  {filtered.length?<div className="project-grid">{filtered.map(projectCard)}</div>:<Empty title={state.projects.length?'Пока ничего не найдено':'С чего начнем?'} description={state.projects.length?'Попробуйте другой фильтр или название.':'Добавьте первый проект — шарф, шапку или любую другую идею. Здесь будут фотографии, материалы и время вашей работы.'}>{!state.projects.length&&<><button className="button primary" onClick={()=>open({type:'project'})}><Plus size={18}/>Создать первый проект</button><button className="text-button" onClick={()=>navigate('yarn')}>Сначала разобрать пряжу <ChevronRight size={16}/></button></>}</Empty>}
 </>}
 {current&&<>
 <div className="detail-meta"><span className={`badge ${current.status}`}>{statusLabels[current.status]}</span>{current.archived&&<span className="badge">В архиве</span>}{current.historical&&<span className="badge">Расход учтен ранее</span>}<span>Начало: {dateLabel(current.start_date)}</span><span>Завершение: {current.end_date?dateLabel(current.end_date):current.end_month?`${current.end_month.slice(5)}.${current.end_month.slice(0,4)} (месяц)`:'Не указано'}</span></div>
 <div className="detail-layout"><div className="detail-main">
 <section className="panel photos-panel"><div className="panel-title"><h2>Фотографии</h2><label className="button secondary upload-label"><ImagePlus size={16}/>{busy?'Загрузка…':'Добавить фото'}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,current);e.target.value='';}}/></label></div>{state.photos.some(p=>p.project_id===current.id)?<div className="photo-gallery">{state.photos.filter(p=>p.project_id===current.id).map(photo=><a key={photo.id} href={`/api/photos/${photo.id}`} target="_blank" rel="noreferrer"><img src={`/api/photos/${photo.id}`} alt={current.title}/></a>)}</div>:<div className="photo-empty"><Skein/><p>Сохраните первый стежок и готовую работу</p></div>}</section>
 <section className="panel"><div className="panel-title"><h2>Пряжа в проекте</h2><button className="button secondary" disabled={busy||!state.yarns.length} onClick={()=>open({type:'consume',project:current})}><Plus size={16}/>Указать расход</button></div>{!state.yarns.length?<p className="muted">Сначала <button className="inline-link" onClick={()=>{navigate('yarn');open({type:'yarn'});}}>добавьте пряжу в банк</button>.</p>:state.usage.filter(u=>u.project_id===current.id).length?<div className="materials">{state.usage.filter(u=>u.project_id===current.id).map(u=>{const y=state.yarns.find(y=>y.id===u.yarn_id)!;return <div className="material" key={u.yarn_id}><span className="swatch" style={{background:y.color_hex}}/><div><strong>{y.manufacturer} {y.name}</strong><small>{y.color}</small></div><strong>{number(u.grams)} г</strong><button className="icon-button" title="Изменить расход" aria-label={`Изменить расход ${y.name}`} onClick={()=>open({type:'consume',project:current,yarnId:y.id})}><SquarePen size={16}/></button></div>;})}</div>:<p className="muted">Выберите пряжу и укажите, сколько граммов уже использовали.</p>}{current.quantity>1&&<p className="hint">Здесь указан расход на всю партию из {current.quantity} шт.</p>}</section>
 <section className="panel"><div className="panel-title"><h2>Сеансы работы</h2><span className="muted">{state.sessions.filter(s=>s.project_id===current.id).length}</span></div>{state.sessions.filter(s=>s.project_id===current.id).length?<div className="sessions">{state.sessions.filter(s=>s.project_id===current.id).map(s=><div key={s.id}><Clock3 size={18}/><div><strong>{duration(sessionSeconds(s))}{s.started_at&&!s.ended_at&&' · идет сейчас'}</strong><small>{s.note||(s.manual_seconds?'Добавлено вручную':new Date(s.started_at!).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</small></div>{!(s.started_at&&!s.ended_at)&&<button className="icon-button" aria-label="Исправить сеанс" onClick={()=>open({type:'time',project:current,session:s})}><SquarePen size={15}/></button>}</div>)}</div>:<p className="muted">Запустите таймер или добавьте время вручную.</p>}</section>
 <SourceNotes project={current}/>
 {current.notes&&<section className="panel"><h2>Параметры и заметки</h2><p className="notes">{current.notes}</p></section>}
 </div><div className="detail-side">{timerPanel(current)}
 {current.source_data?<LegacyCosts project={current}/>:<section className="panel cost-panel"><h2>Стоимость работы</h2><dl><div><dt>Пряжа</dt><dd>{money(current.yarn_cost)}</dd></div><div><dt>Другие материалы</dt><dd>{money(current.other_cost)}</dd></div><div><dt>Работа · {money(current.rate)}/ч</dt><dd>{money((current.seconds+(active?.project_id===current.id?activeSeconds:0))/3600*Number(current.rate))}</dd></div><div className="cost-total"><dt>{current.cost_incomplete?'Известная часть':'Расчетная стоимость'}</dt><dd>{money(Number(current.yarn_cost)+Number(current.other_cost)+(current.seconds+(active?.project_id===current.id?activeSeconds:0))/3600*Number(current.rate))}</dd></div>{current.quantity>1&&<div><dt>В среднем за штуку</dt><dd>{money((Number(current.yarn_cost)+Number(current.other_cost)+current.seconds/3600*Number(current.rate))/current.quantity)}</dd></div>}<div><dt>Назначенная цена / шт.</dt><dd>{current.price===null?'Не задана':money(current.price)}</dd></div></dl>{current.cost_incomplete&&<p className="notice">Стоимость части пряжи неизвестна. Итог неполный.</p>}</section>}
 <section className="project-actions">{!current.archived&&<><label className="field"><span>Статус проекта</span><select aria-label="Статус проекта" value={current.status} disabled={busy} onChange={e=>act({type:'project.status',id:current.id,version:current.version,status:e.target.value},'Статус обновлен')}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{current.status!=='completed'&&<button className="button primary full" disabled={busy} onClick={()=>act({type:'project.status',id:current.id,version:current.version,status:'completed'},'Изделие готово!')}><Check size={17}/>Завершить проект</button>}</>}
 <button className="button secondary full" disabled={busy} onClick={async()=>{const r=await act({type:'project.repeat',id:current.id},'Создан новый проект по образцу');if(r?.id)setSelected(r.id);}}><Copy size={16}/>Связать еще раз</button><button className="text-button" disabled={busy} onClick={()=>act({type:'template.save',id:current.id},'Шаблон сохранен')}><BookOpen size={16}/>Сохранить как шаблон</button><button className="text-button" disabled={busy} onClick={()=>act({type:'project.archive',id:current.id,version:current.version,archived:!current.archived},current.archived?'Проект возвращен из архива':'Проект в архиве')}><Archive size={16}/>{current.archived?'Вернуть из архива':'Убрать в архив'}</button></section>
 </div></div>
 </>}
 {!yarn&&tab==='yarn'&&<><div className="toolbar"><p className="muted">{state.yarns.length} цветов · {number(state.yarns.reduce((s,y)=>s+Number(y.balance),0))} г в запасе</p><label className="search"><Search size={17}/><input aria-label="Поиск пряжи" placeholder="Название, цвет или состав" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{state.yarns.length?<div className="yarn-grid">{state.yarns.filter(y=>`${y.manufacturer} ${y.name} ${y.color} ${y.composition}`.toLowerCase().includes(search.toLowerCase())).map(y=><button className="yarn-card" key={y.id} onClick={()=>setSelectedYarn(y.id)}><div className="yarn-art" style={{background:`${y.color_hex}15`}}><Skein color={y.color_hex}/></div><div><small>{y.manufacturer}</small><h3>{y.name}</h3><p>{y.color}</p><div className="yarn-card-bottom"><strong>{number(y.balance)} <small>г</small></strong><span>{number(y.skein_weight)} г / {y.skein_length?`${number(y.skein_length)} м`:'метраж не указан'}</span></div></div></button>)}</div>:<Empty title="Ваша коллекция начинается с мотка" description="Добавьте пряжу, которую уже купили. Цвет, состав и остаток будут под рукой, когда появится новая идея."><button className="button primary" onClick={()=>open({type:'yarn'})}><Plus size={18}/>Добавить первую пряжу</button></Empty>}</>}
 {yarn&&<><div className="yarn-summary"><Skein color={yarn.color_hex}/><div><p className="muted">Осталось в банке</p><strong>{number(yarn.balance)} <span>г</span></strong><p>{yarn.composition}</p><small>{number(yarn.skein_weight)} г в мотке{yarn.skein_length?` · ${number(yarn.skein_length)} м`:''}</small></div></div><section className="panel"><div className="panel-title"><h2>Поступления</h2><span className="muted">Отдельная запись для каждой покупки</span></div>{state.receipts.filter(r=>r.yarn_id===yarn.id).length?<div className="table-wrap"><table><thead><tr><th>Дата / партия</th><th>Получено</th><th>Осталось</th><th>Стоимость</th><th/></tr></thead><tbody>{state.receipts.filter(r=>r.yarn_id===yarn.id).map(r=><tr key={r.id}><td>{dateLabel(r.purchased_on)}<small>{r.dye_lot||r.note}</small></td><td>{number(r.grams)} г</td><td>{number(r.balance)} г</td><td>{r.cost===null?'Неизвестна':money(r.cost)}</td><td><button className="text-button" onClick={()=>open({type:'adjust',receipt:r})}>Уточнить остаток</button></td></tr>)}</tbody></table></div>:<div className="inline-empty"><p>Укажите, сколько этой пряжи у вас есть.</p><button className="button primary" onClick={()=>open({type:'receive',yarn})}><Plus size={17}/>Добавить поступление</button></div>}</section><section className="panel"><h2>История движения</h2><div className="movement-list">{state.movements.filter(m=>m.yarn_id===yarn.id).map(m=><div key={m.id}><span className={Number(m.grams)>0?'movement-icon positive':'movement-icon'}>{Number(m.grams)>0?<Plus size={17}/>:<ArrowUpRight size={17}/>}</span><div><strong>{{receipt:'Поступление',consumption:'Расход на изделие',return:'Возврат пряжи',adjustment:'Уточнение остатка'}[m.kind]}</strong><small>{state.projects.find(p=>p.id===m.project_id)?.title??m.reason??''} · {new Date(m.created_at).toLocaleDateString('ru-RU')}</small></div><b className={Number(m.grams)>0?'positive':''}>{Number(m.grams)>0?'+':''}{number(m.grams)} г</b></div>)}</div></section></>}
 {tab==='templates'&&!current&&<>{state.templates.length?<div className="template-grid">{state.templates.map(t=><article className="panel template-card" key={t.id}><BookOpen size={24}/><small>{t.category}</small><h2>{t.title}</h2><p>{t.notes||'Модель для нового проекта'}</p><button className="button secondary" onClick={()=>open({type:'project',template:t})}><Plus size={16}/>Начать проект</button></article>)}</div>:<Empty title="Удачные модели стоит сохранить" description="Откройте карточку проекта и нажмите «Сохранить как шаблон». Следующее изделие начнется с готового описания."/>}</>}
 {yarn&&<ImportedPurchases yarn={yarn} state={state}/>}
 {tab==='import'&&<ImportPanel onImported={refresh}/>}
 <footer className="page-footer"><button className="text-button" onClick={()=>open({type:'settings'})}><Settings2 size={14}/>Настройки</button><a href="/api/export" download><Download size={15}/>Скачать данные и фото</a></footer>
 </>}
 </main>{form&&state&&<Forms key={form.type+('project'in form?form.project?.id??'':'')} form={form} state={state} onClose={()=>{setForm(null);setError('');}} onSave={save} busy={busy} error={error}/>}{toast&&<div className="toast" role="status"><span>{toast}</span><button className="icon-button" onClick={()=>setToast('')} aria-label="Закрыть уведомление"><X size={16}/></button></div>}
 </div>;
}
